# Occupation taxonomy: (family, role, title_include, title_exclude, bound)
# bound: 0 = can be done remotely, 1 = partly bound (licence/clearance/client-facing), 2 = physically on-site
X_SEN=["Intern"]
TAX=[
("Software Engineering","Software Engineer",["Software Engineer","Software Developer"],["Test","QA","Embedded","Manager"],0),
("Software Engineering","Frontend Developer",["Frontend","Front-End","Front End","React Developer","Angular Developer"],[],0),
("Software Engineering","Backend Developer",["Backend","Back-End","Back End","Java Developer","Python Developer",".NET Developer","Node.js Developer","Golang"],[],0),
("Software Engineering","Full Stack Developer",["Full Stack","Full-Stack","Fullstack"],[],0),
("Software Engineering","Mobile Developer",["iOS","Android","Mobile Developer","Mobile Engineer","React Native","Flutter"],[],0),
("Software Engineering","QA / Test Engineer",["QA Engineer","Quality Assurance Engineer","Test Engineer","SDET","QA Analyst","Test Automation","QA Tester","Software Tester"],["Manufacturing","Hardware"],0),
("Software Engineering","DevOps / SRE",["DevOps","Site Reliability","SRE","Platform Engineer"],[],0),
("Software Engineering","Cloud Engineer",["Cloud Engineer","AWS Engineer","Azure Engineer","Cloud Architect","GCP Engineer"],[],0),
("Software Engineering","Embedded / Firmware",["Embedded","Firmware"],[],1),
("Software Engineering","Engineering Manager",["Engineering Manager","Director of Engineering","VP of Engineering"],[],1),
("Data & AI","Data Engineer",["Data Engineer"],[],0),
("Data & AI","Data Analyst",["Data Analyst"],[],0),
("Data & AI","Data Scientist",["Data Scientist"],[],0),
("Data & AI","ML Engineer",["Machine Learning Engineer","ML Engineer","MLOps"],[],0),
("Data & AI","AI / LLM Engineer",["AI Engineer","Applied AI","LLM Engineer","Generative AI","GenAI","AI Agent"],[],0),
("Data & AI","Analytics / BI Developer",["BI Developer","Business Intelligence","Power BI","Tableau Developer","Analytics Engineer","Reporting Analyst"],[],0),
("Data & AI","Data Annotation / AI Trainer",["Data Annotator","Data Annotation","AI Trainer","Data Labeling","AI Tutor","Annotation Specialist"],[],0),
("IT & Security","IT Support / Help Desk",["Help Desk","Service Desk","IT Support","Desktop Support","IT Technician"],[],1),
("IT & Security","Systems Administrator",["System Administrator","Systems Administrator","Sysadmin","Linux Administrator","Windows Administrator"],[],0),
("IT & Security","Network Engineer",["Network Engineer","Network Administrator"],[],1),
("IT & Security","Security Analyst / SOC",["Security Analyst","SOC Analyst","Cybersecurity Analyst","Information Security Analyst"],["Clearance"],1),
("IT & Security","Security Engineer",["Security Engineer","Cloud Security","Application Security","Penetration Tester"],["Clearance"],1),
("IT & Security","Database Administrator",["Database Administrator","DBA","Database Engineer"],[],0),
("IT & Security","IT Project Manager",["IT Project Manager","Technical Project Manager","Scrum Master","Agile Coach"],[],0),
("Enterprise Apps","Salesforce",["Salesforce"],[],0),
("Enterprise Apps","ServiceNow",["ServiceNow"],[],0),
("Enterprise Apps","SAP",["SAP "],[],0),
("Enterprise Apps","Oracle",["Oracle"],[],0),
("Enterprise Apps","Workday",["Workday"],[],0),
("Enterprise Apps","Microsoft Dynamics",["Dynamics 365","D365","Dynamics CRM"],[],0),
("Enterprise Apps","NetSuite",["NetSuite"],[],0),
("Enterprise Apps","HubSpot",["HubSpot"],[],0),
("Product & Design","Product Manager",["Product Manager"],["Marketing"],1),
("Product & Design","Product Owner / BA",["Product Owner","Business Analyst","Business Systems Analyst"],[],0),
("Product & Design","UX / Product Designer",["UX Designer","UI Designer","UI/UX","Product Designer","UX Researcher"],[],0),
("Product & Design","Graphic Designer",["Graphic Designer","Visual Designer","Presentation Designer"],[],0),
("Product & Design","Video Editor / Motion",["Video Editor","Motion Designer","Motion Graphics","Animator"],[],0),
("Product & Design","Technical Writer",["Technical Writer","Documentation Specialist","Instructional Designer"],[],0),
("Marketing","Content / Copywriter",["Content Writer","Copywriter","Content Marketing","Content Strategist","Content Creator","Content Editor"],[],0),
("Marketing","SEO / AEO",["SEO","Search Engine Optimization"],[],0),
("Marketing","Paid Media / PPC",["Paid Media","Paid Search","Paid Social","PPC","Performance Marketing","Media Buyer"],[],0),
("Marketing","Social Media",["Social Media"],[],0),
("Marketing","Email / Lifecycle",["Email Marketing","Lifecycle Marketing","CRM Marketing","Retention Marketing"],[],0),
("Marketing","Marketing Ops / Automation",["Marketing Operations","Marketing Automation","MarTech"],[],0),
("Marketing","Growth / Demand Gen",["Growth Marketing","Demand Generation","Demand Gen","Growth Marketer"],[],0),
("Marketing","Marketing Manager",["Marketing Manager","Brand Manager","Product Marketing"],[],1),
("Sales & GTM","SDR / BDR",["Sales Development Representative","Business Development Representative","SDR","BDR"],[],0),
("Sales & GTM","Inside Sales",["Inside Sales","Telesales","Sales Representative"],["Outside","Field","Territory"],0),
("Sales & GTM","Lead Gen / Appt Setter",["Lead Generation","Appointment Setter","Cold Caller"],[],0),
("Sales & GTM","Account Executive",["Account Executive"],[],1),
("Sales & GTM","Account Manager",["Account Manager"],["Territory"],1),
("Sales & GTM","Customer Success",["Customer Success"],[],0),
("Sales & GTM","Sales / RevOps",["Sales Operations","Revenue Operations","RevOps","Sales Analyst","CRM Administrator"],[],0),
("Sales & GTM","GTM Engineer",["GTM Engineer","Go-To-Market Engineer","Growth Engineer"],[],0),
("Sales & GTM","Sales Engineer",["Sales Engineer","Solutions Engineer","Solutions Consultant","Pre-Sales"],[],1),
("Customer Support","Customer Service Rep",["Customer Service Representative","Customer Service Specialist","Customer Service Associate","Customer Care"],["Store","Retail","Branch","Bank Teller"],0),
("Customer Support","Customer / Tech Support",["Customer Support","Technical Support","Support Specialist","Support Engineer","Product Support"],["Field"],0),
("Customer Support","Call Center Agent",["Call Center","Contact Center","Customer Service Agent"],[],0),
("Customer Support","Chat / Email Support",["Chat Support","Email Support","Live Chat","Trust & Safety","Content Moderator"],[],0),
("Finance & Accounting","Staff / Senior Accountant",["Staff Accountant","Senior Accountant","Accountant","General Ledger","GL Accountant"],["Clerk"],0),
("Finance & Accounting","Bookkeeper",["Bookkeeper","Bookkeeping","Accounting Clerk"],[],0),
("Finance & Accounting","AP / AR Specialist",["Accounts Payable","Accounts Receivable","AP Specialist","AR Specialist","Collections Specialist","Billing Specialist"],[],0),
("Finance & Accounting","Payroll",["Payroll"],[],0),
("Finance & Accounting","FP&A / Financial Analyst",["Financial Analyst","FP&A","Finance Analyst"],[],0),
("Finance & Accounting","Tax",["Tax Associate","Tax Accountant","Tax Senior","Tax Analyst","Tax Preparer","Tax Manager"],[],1),
("Finance & Accounting","Audit",["Auditor","Audit Associate","Audit Senior","Internal Audit"],[],1),
("Finance & Accounting","Controller",["Controller","Accounting Manager"],[],1),
("HR & Recruiting","Recruiter",["Recruiter","Talent Acquisition"],[],0),
("HR & Recruiting","Sourcer",["Sourcer","Sourcing Specialist","Recruiting Coordinator"],[],0),
("HR & Recruiting","HR Generalist / Ops",["HR Generalist","HR Coordinator","HR Specialist","People Operations","HR Assistant","Benefits Specialist"],[],0),
("HR & Recruiting","HRIS",["HRIS"],[],0),
("Ops & Admin","Executive Assistant",["Executive Assistant"],[],1),
("Ops & Admin","Virtual Assistant",["Virtual Assistant","Remote Assistant"],[],0),
("Ops & Admin","Administrative Assistant",["Administrative Assistant","Office Assistant","Administrative Coordinator"],[],2),
("Ops & Admin","Data Entry",["Data Entry"],[],0),
("Ops & Admin","Operations Analyst",["Operations Analyst","Business Operations","Operations Specialist"],[],0),
("Ops & Admin","Project / Program Coordinator",["Project Coordinator","Program Coordinator","Project Manager","Program Manager"],["Construction","IT Project"],1),
("Ops & Admin","Procurement / Purchasing",["Procurement","Purchasing","Buyer","Sourcing Analyst"],[],0),
("Ops & Admin","Supply Chain / Logistics Analyst",["Supply Chain Analyst","Logistics Coordinator","Logistics Analyst","Demand Planner","Inventory Analyst"],[],1),
("Healthcare Admin","Medical Coder",["Medical Coder","Coding Specialist","Coding Auditor","Risk Adjustment Coder","Inpatient Coder","Outpatient Coder"],[],0),
("Healthcare Admin","Medical Biller / Rev Cycle",["Medical Biller","Medical Billing","Revenue Cycle","Patient Account","Billing Representative"],[],0),
("Healthcare Admin","Prior Authorization",["Prior Authorization","Authorization Specialist","Insurance Verification","Benefits Verification","Referral Coordinator"],[],0),
("Healthcare Admin","Credentialing",["Credentialing"],[],0),
("Healthcare Admin","Medical Scribe",["Medical Scribe","Scribe"],[],1),
("Healthcare Admin","Claims Processor",["Claims Processor","Claims Examiner","Claims Specialist","Claims Analyst"],[],0),
("Legal & Compliance","Paralegal / Legal Assistant",["Paralegal","Legal Assistant","Legal Secretary","Litigation Support"],[],0),
("Legal & Compliance","Contract Manager",["Contract Manager","Contracts Manager","Contract Administrator","Contracts Specialist"],[],0),
("Legal & Compliance","Compliance / KYC / AML",["Compliance Analyst","KYC","AML","Anti-Money Laundering","Compliance Specialist"],[],0),
("Legal & Compliance","Attorney",["Attorney","Associate Counsel","Corporate Counsel","Lawyer"],[],1),
("Insurance & Lending","Underwriter",["Underwriter","Underwriting"],[],0),
("Insurance & Lending","Loan / Mortgage Processor",["Loan Processor","Mortgage Processor","Loan Officer Assistant","Closing Coordinator","Loan Closer"],[],0),
("Insurance & Lending","Insurance Agent / CSR",["Insurance Agent","Insurance Account Manager","Licensed Insurance","Insurance Customer Service"],[],1),
("Insurance & Lending","Claims Adjuster",["Claims Adjuster","Claims Representative"],["Field"],1),
("Design Engineering","CAD / Drafter",["Drafter","CAD Designer","CAD Technician","AutoCAD","Revit"],[],0),
("Design Engineering","BIM / Architectural Designer",["BIM","Architectural Designer","Architectural Drafter"],[],0),
("Design Engineering","Mechanical Design Engineer",["Mechanical Design Engineer","Mechanical Engineer","Design Engineer"],["Field"],1),
("Design Engineering","Civil / Structural Engineer",["Civil Engineer","Structural Engineer"],[],1),
("Design Engineering","Electrical Engineer",["Electrical Engineer"],[],1),
("On-site Control","Registered Nurse",["Registered Nurse","RN "],[],2),
("On-site Control","Truck Driver",["Truck Driver","CDL"],[],2),
("On-site Control","Retail Sales Associate",["Retail Sales Associate","Store Associate","Cashier"],[],2),
("On-site Control","Warehouse Associate",["Warehouse Associate","Warehouse Worker","Picker","Forklift"],[],2),
("On-site Control","Electrician / Technician",["Electrician","HVAC Technician","Maintenance Technician"],[],2),
("Software Engineering","Systems / Solutions Architect",["Systems Engineer","Solutions Architect","Software Architect","Enterprise Architect","Technical Architect"],[],0),
("Sales & GTM","Sales Manager / Director",["Sales Manager","Sales Director","Head of Sales","VP of Sales","VP Sales","Regional Sales"],[],1),
("Education","Teacher / Tutor",["Teacher","Tutor","Instructor","Professor","Faculty","Curriculum"],[],1),
("Healthcare Clinical","Therapist / Clinician",["Therapist","Psychologist","Counselor","Social Worker","Pathologist","Physician","Pharmacist","Dentist","Dental","Clinician","Medical Assistant","Psychiatr","Nurse Practitioner"],[],2),
("Healthcare Clinical","Nurse / Aide / Caregiver",["Nurse","LPN","CNA","Home Health Aide","HHA","Caregiver","Direct Support Professional","DSP","Patient Care","Nursing"],[],2),
("On-site Control","Driver / Delivery",["Driver","Delivery","Courier"],[],2),
("On-site Control","Automotive / Field Technician",["Technician","Detailer","Mechanic","Automotive","Installer","Lot Attendant","Parts Associate"],[],2),
("On-site Control","Logistics / Warehouse Ops",["Logistics Associate","Material Handler","Fulfillment","Package Handler","Loader","Operator"],[],2),
("On-site Control","Hospitality / Food / Retail",["Cook","Server","Barista","Dishwasher","Housekeep","Front Desk","Chef","Bartender","Crew Member","Store","Sales Associate","Merchandiser"],[],2),
("Ops & Admin","Site / General Manager",["General Manager","Branch Manager","Regional Manager","Site Manager","Plant Manager","Operations Manager","Property Manager"],[],2),
("Leadership","Director / VP / Head (other)",["Director","Vice President","VP,","VP ","Head of","Chief "],[],1),
]
